application: familybook-hack
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- appstats: on

handlers:
- url: /.*
  script: main.application

libraries:
  - name: django
    version: 1.4